services:
  opencv_container:
    container_name: image_processing_with_opencv_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../src:/work
    working_dir: /work
    tty: true
